FROM node:18-alpine

WORKDIR /app

# Установка nodemon для hot-reload
RUN npm install -g nodemon

# Копируем package.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
