FROM node:18-alpine

WORKDIR /app

# Устанавливаем nodemon глобально для hot reload
RUN npm install -g nodemon

COPY package*.json ./
RUN npm install

COPY . .

RUN mkdir -p /knowledge-base

EXPOSE 3000

CMD ["nodemon", "server.js"]
